### ISSUE TITLE
Crash while converting

### ISSUE THREAD

**Issue by AstraeaZero** [tmokmss/Osu2Saber#1]
App crash after click proces on two PCs with Windows 10 with latest update, app creating two folders, where Output is empty.
Can i help you with something? This project is very interesting and a lot of VR stay with Beatsaber because this is really good game. Have a good day and sorry for bad english

**Comment by tmokmss** [comment]
Thanks for the report!
Hmm that's possibly because of your .zip or .osz archives.
Could you provide me with the archives you're trying to convert? 
I'll test them in my environment.

**Comment by AstraeaZero** [comment]
Np, i used two songs, one in .osz
https://bloodcat.com/osu/s/21342
https://bloodcat.com/osu/s/673138
after crash, i try to take extracted song (little travel) from osu folder and pack it in .zip with this same result.
i have all redistributed libs installed from old to latest version
This songs are in two formats, one in old osu beatmaping method, second in new.
Edit: I try on 0.7.0 and 0.6.1

**Comment by tmokmss** [comment]
In my environment I successfully converted those maps without any problem...

To locate your problem, I added error logging feature in [v0.7.1](https://github.com/tmokmss/Osu2Saber/releases/tag/v0.7.1).
The error log file should appear in the same directory as `Osu2Saber.exe`. (e.g. `Log_20181014114500.txt`)
Could you run again and report with the log file?

Sorry for the inconvenience! Thanks.

**Comment by AstraeaZero** [comment]
Log returned in Polish Language:
"Error while converting - 21342 DJ Command - Smooooch (Akiba Kobo Mix).osz
System.ArgumentOutOfRangeException: Indeks był spoza zakresu. Musi mieć wartość nieujemną i mniejszą niż rozmiar kolekcji.
Nazwa parametru: index
   w System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   w Osu2Saber.Model.Osu2BsConverter.ProcessAll()
   w Osu2Saber.Model.BatchProcessor.ConvertBeatmap(OszProcessor oszp)
   w Osu2Saber.Model.BatchProcessor.Process(String oszPath)"

**Comment by KrypteckLair** [comment]
error when attempting to convert this https://osu.ppy.sh/beatmapsets/734135#osu/1553356 ;-;
if it works in your enviroment can you send me it plz?

**Comment by AstraeaZero** [comment]
> error when attempting to convert this https://osu.ppy.sh/beatmapsets/734135#osu/1553356 ;-;
> if it works in your enviroment can you send me it plz?

Man, at this moment, we helping with fix this app for everyone, not for sending songs via priv. Wait for reply from author. I think, he work really hard at this program.

**Comment by KrypteckLair** [comment]
I never said he was not working hard.. why so hostile? I was only asking

**Comment by AstraeaZero** [comment]
> I never said he was not working hard.. why so hostile? I was only asking

Hositle? Noo, i mean, this is place for post project etc, not for asking author about convert song themself, if you have a problem, download version 0.7.1 and post there a log file, with this you can help with fix problem. Just open file in app folder named "Log_20181014114500.txt" or something simular, open it with notepad and post all log there.

**Comment by tmokmss** [comment]
Sorry for the late reply!
With your error log, I managed to locate the source of the problem.
I'm not sure why this error only happens on your environment though...
Anyway I'll be working on this problem this weekend.

It'll be great if we can chat on Discord for faster communication btw.
Thanks.

**Comment by AstraeaZero** [comment]
Np. After work i can join to your discord chat. Send me a link.
I have one include. This can't be a problem with Unicode or something with language? I remember one time when i using one app with this same problem. But there fix was a locale emulator for emulating japanese Unicode.

**Comment by tmokmss** [comment]
I'm here @tmokmss : https://discord.gg/beatsabermods
Contact me when i'm online.

Yea it's highly possible that it's a locale matter. Can you try a locale emulator?

Also I'd like to confirm that your unzip process was successfully done.  There should be an unzipped folder (which is in a `osz` directory) and it contains all .osu files.

**Comment by AstraeaZero** [comment]
What is your nick on this satan communicator? :>
Btw, what is your country? Because i must select it in locale emulator
edit, ok i found it, i send you a friend request form nickname AstraeaZero or Kwiatek146

**Comment by tmokmss** [comment]
It was a problem due to polish locale when parsing float number.
Refer to: https://stackoverflow.com/questions/5592950/why-do-i-get-a-formatexception-when-converting-a-string-to-a-float
