### ISSUE TITLE
formula to convert osu beat timings to beat saber beat timings

### ISSUE THREAD

**Issue by inikishev** [tmokmss/Osu2Saber#7]
how do you convert osu timings to beat saber timings? I can't figure it out it says osu is in ms and beat saber is in beats so how do you convert between the two? I got bpm from beatsaber and divided it by 60000 to obtain beats per millisecond and then if I multiply beatsaber timings I am supposed to get osu timings? but it deosn't work at all

**Comment by tmokmss** [comment]
Hi @idkman2021 Here's the code for that:

https://github.com/tmokmss/Osu2Saber/blob/ad1682b0a7eb2fe2971ee5a744fee21f250ec53b/Osu2Saber/Model/Algorithm/ConvertAlgorithm.cs#L266-L271

where `timeMs` = osu timing and the returned value = beat saber timing.

idk if it still works though as the last time I checked was four years ago

**Comment by inikishev** [comment]
thank you can confirm it still works

**Comment by tmokmss** [comment]
glad to hear that!
